@startuml Academy Class Diagram

class Academy   {
    + Branch: Branch
    + Title: string
    + Phone: string
    + AddressLine1: string
    + AddressLine2: string
    + Country: string
    + City: string
    + Region: string
    + State: string
    + PostalCode: Number
    + Lat: Number
    + Lng: Number

    + Filter(): Academy[]
}

Academy <|-- FullBaseEntity: Inheritance
 
@enduml