@startuml Fan Class Diagram

class Fan {
    + FullName: string
    + PhoneNumber: string
    + Tckn: string
    + companion: bool
    + wheelchair: bool
    + Events: Event[]
    + Companion: Companion
}

Fan --|> BaseEntity: Inheritance
Fan "many" o-- "many" Event: Aggregation
Fan "1" *-- "0" Companion: Composition

@enduml
