@startuml Class Diagram

title Sport Club Class Diagram

skinparam SequenceMessageAlignment center

!include ./Shared/Shared.puml
!include ./Enums/BranchTypes.puml
!include ./Enums/GameStatuses.puml
!include ./Enums/Languages.puml
!include ./Enums/PersonTypes.puml
!include ./Enums/PlayerPositions.puml
!include ./Enums/StaffPositions.puml
!include ./Enums/TeamTypes.puml

!include ./Academy/Academy.puml
!include ./Branch/Branch.puml
!include ./Content/Content.puml
!include ./Event/Event.puml
!include ./Event/Fan.puml
!include ./Event/Companion.puml
!include ./Gallery/Gallery.puml
!include ./Gallery/Image.puml
!include ./News/Category.puml
!include ./News/News.puml
!include ./Product/Product.puml
!include ./ShortUrl/ShortUrl.puml
!include ./Store/Store.puml
!include ./Team/Person.puml
!include ./Team/Team.puml
!include ./Tournament/Club.puml
!include ./Tournament/Game.puml
!include ./Tournament/Penalty.puml
!include ./Tournament/Phase.puml
!include ./Tournament/Rule.puml
!include ./Tournament/Tournament.puml
!include ./Video/Video.puml

@enduml