@startuml Category Class Diagram

class Category  {
    + Language: Languages
    + Title: string 
    + Image: string
    + News: News[] 

    + Filter(): Category[]
    + AddNews(): News
}

Category <|-- BaseEntity: Inheritance
Category <-- Languages
Category "1" -- "many" News: Composition

note left of Category::News 
Kategoriye ait haberler
end note
 
@enduml