@startuml News Class Diagram

class News  {
    + Category: Category
    + Gallery: Gallery
    + Title: string 
    + Image: string 
    + Description: string 
    + Slide: bool 
    + Constant: bool 
    + PublishDatetime:Datetime 

    + createOverview(length): string
    + search(): News[]
}

News <|-- FullBaseEntity: Inheritance
News "0" o-- "1" Gallery: Aggregation

note right of News::Category 
 Haberin sadece <b>bir</b> kategorisi olabilir
 end note

note right of News::Gallery 
Haber duruma göre <b>bir</b> adet galeri ile ilişkilendirilebilir
end note
 
@enduml