@startuml Content Class Diagram

class Content {
    + Language: Languages
    + Title: string
    + Image: string
    + Body: string

    + Search(): Content[]
}

Content --|> FullBaseEntity: Inheritance
Content <-- Languages
@enduml
