@startuml Content Class Diagram

class Content {
    + Language: Languages
    + Title: string
    + Image: string
    + Description: string

    + Filter(): Content[]
}

Content --|> FullBaseEntity: Inheritance
Content <-- Languages
@enduml
