@startuml Companion Class Diagram

class Companion {
    + Name: string
    + Phone: string
    + Tckn: string
    + Fan: Fan
}

Companion --|> BaseEntity: Inheritance
Companion "1" *-- "1" Fan

@enduml
