@startuml Event Class Diagram

class Event {
    + Title: string
    + Capacity: int
    + Datetime: Datetime
    + Fans: Fan[]
}

Event --|> BaseEntity: Inheritance

note right of Event::Fans
Bir maça (iç saha) gidebilecek max engelli taraftar sayısı <b>102</b>'dir <u>(Refakatçi dahil)</u>
end note

@enduml
