@startuml Store Class Diagram

class Store {
    + Title: string
    + Phone: string
    + AddressLine1: string
    + AddressLine2: string
    + Country: string
    + City: string
    + Region: string
    + State: string
    + PostalCode: Number
    + Lat: Number
    + Lng: Number
    + WeekdayOpenTime: string
    + WeekdayCloseTime: string
    + WeekendOpenTime: string
    + WeekendCloseTime: string
    + Image: string

    + GetAddress(): Store
    + Filter: Store[]
}

Store --|> BaseEntity: Inheritance

@enduml
