@startuml Tournament Class Diagram

class Tournament {
    + Team: Team
    + Title: string
    + Image: string
    + Favorite: bool
    + Phases: Phase[]

    + Filter: Tournament[]
    + AddPhase(): Phase
    + SetFavorite()
}

Tournament --|> BaseEntity: Inheritance
Tournament "1" o-- "1" Team: Composition
Tournament "1" o-- "many" Phase: Composition

note right of Tournament::Phases
Turnuvanın aşamaları
end note

@enduml
