@startuml ShortUrl Class Diagram

class ShortUrl  {
    + Link: string
    + LongUrl: string
    + Special: bool

    + Find: ShortUrl

}

ShortUrl <|-- BaseEntity: Inheritance

note top of ShortUrl: Bit.ly api kullanılarak kısa url oluşturulacak. Özel url istenirse api kullanılmadan uzantı verilecek.

 
@enduml