@startuml Gallery Class Diagram

class Gallery  {
    + Language: Languages
    + Title: string
    + Images: Image[]

    + Filter: Gallery[]
}

note right of Gallery::Images 
"Bir galeriye eklenebilecek maksimum görsel sayısı <b><u>20</u></b> olacak"
end note

Gallery <|-- FullBaseEntity: Inheritance
Gallery <-- Languages 
Gallery "1" *-- "many" Image: Composition
 
@enduml