@startuml Staff Position Enums

enum StaffPositions {
    COACH
    ASSISTANTCOACH
    GOALKEEPINGCOACH
    CONDITIONER
    TEAMMANAGER
    PERFORMANCECOACH
    FITNESCOACH
    MATCHANDPERFORMANCEANALTST
    DOCTOR
    MASSEUR
    PHYSIOTHERAPIST
    KTIMAN
}
 
@enduml