@startuml Team Class Diagram

class Team  {
    + TeamType: TeamType
    + Branch: Branch
    + Title: string
    + Image: string
    + Homepage: bool
    + Persons: Person[]

    + AddPerson(): Person
}

Team <|-- FullBaseEntity: Inheritance
Team *-- "many" Person: Composition
Team --> TeamTypes

note right of Team::Homepage
Takımı Anasayfada görüntüle
end note

note right of Team::Persons
Takıma ait sporcu ve teknik ekip listesi
end note

@enduml